language: ruby
branches:
  only:
    - master
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
services:
  - mongodb
rvm:
  - "2.4.6"
  - "2.5.5"
  - "2.6.3"
gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile
env:
  - BACKEND=mongoid
  - BACKEND=active_record
jobs:
  exclude:
  - rvm: "2.4.6"
    gemfile: gemfiles/rails6.0.gemfile
